In [1]:
import numpy as np

In [3]:
# problem a
x = [[2]]
y = [8]
w = [4]
np.matmul(x,w)

array([8])

In [4]:
# problem b

X = [[0]]
y = [8]

# no solution

In [7]:
# problem c
X = [[2, 4]]
y = [8]
np.matmul(x,w)
# no solution

array([[4, 2]])

In [28]:
# problem d
X = [[2, 4],[0, 1]]
y = [2,-3]
w = [[2,1],[0,3]]
np.subtract(X,w)
# no solution

array([[ 0,  3],
       [ 0, -2]])

In [20]:
# problem e
X = [[2,4],[0,1],[9,5]]
y = [8,3,1]
np.subtract(X,w)
# no solution

ValueError: operands could not be broadcast together with shapes (3,2) (2,2) 

In [22]:
# problem f
X = [[2,2],[3,3]]
y = [4,6]
w = [1,1]
np.matmul(X,w)

array([4, 6])

In [17]:
# problem g
# no solution

In [30]:
# problem h
X = [[1,0],[0,1]]
w = [8,6]
y = [8,6]
np.linalg.solve(X,w)

array([8., 6.])

In [29]:
# problem i
X = [[1,1,0],[1,0,1]]
w = [5,3,1]
y = [8,6]
np.matmul(X,w)
# no solution

array([8, 6])

In [27]:
# problem j
X = [[1,0],[1,1]]
w = [8,-2]
y = [8,6]
np.matmul(X,w)

array([8, 6])